openapi: 3.0.3
info:
  title: API de Autenticación
  description: API para gestionar la autenticación de usuarios, incluyendo registro, inicio de sesión, cierre de sesión y autenticación con Auth0.
  version: 1.0.0
servers:
  - url: http://localhost:5000
    description: Servidor local de desarrollo

paths:
  /register:
    post:
      summary: Registra un nuevo usuario
      requestBody:
        description: Datos del usuario a registrar
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: usuario123
                email:
                  type: string
                  example: usuario@example.com
                password:
                  type: string
                  example: contraseñaSegura123
      responses:
        '201':
          description: Usuario registrado exitosamente
        '400':
          description: El usuario o el correo electrónico ya existe

  /login:
    post:
      summary: Inicia sesión
      requestBody:
        description: Credenciales del usuario
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: usuario@example.com
                password:
                  type: string
                  example: contraseñaSegura123
      responses:
        '200':
          description: Inicio de sesión exitoso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Inicio de sesión exitoso.
                  access_token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR...
                  username:
                    type: string
                    example: usuario123
        '401':
          description: Credenciales inválidas

  /validate-token:
    get:
      summary: Valida el token JWT
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Token válido
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Acceso concedido
                  email:
                    type: string
                    example: usuario@example.com
        '401':
          description: Token inválido o expirado

  /logout:
    post:
      summary: Cierra sesión
      responses:
        '200':
          description: Cierre de sesión exitoso
        '500':
          description: Error durante el cierre de sesión

  /auth0-login:
    get:
      summary: Redirige al usuario a Auth0 para autenticación
      responses:
        '302':
          description: Redirección a Auth0

  /callback:
    get:
      summary: Maneja el callback de Auth0
      responses:
        '302':
          description: Redirección con token JWT a la interfaz de usuario
        '400':
          description: Error en la autenticación con Auth0
        '500':
          description: Error interno del servidor

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        email:
          type: string
        password:
          type: string
